$ExportFileName = 'Groupnames.csv'

$ExportPathPredifined = 'C:\Users\mohamed.elshair\Desktop\Groups'

$ExportPathFull = "$ExportPathPredifined\$ExportFileName"

Get-ADGroup -Filter * | select SamAccountName | Export-Csv $ExportPathFull -NoTypeInformation

$groups = Import-Csv C:\Users\mohamed.elshair\Desktop\Groups\GroupsAray.csv -Delimiter "," | Out-String



foreach ( $groups in $groups ) {Get-ADGroupMember -Identity $groups | select SamAccountName | export-csv "C:\Users\mohamed.elshair\Desktop\Groups\Groups-Exported\$groups.csv" -NoTypeInformation } 




$Groups = "WseRemoteWebAccessUsers",
"WseAllowShareAccess",
"WseAllowComputerAccess",
"WseAllowMediaAccess",
"WseAllowAddInAccess",
"WseAllowDashboardAccess",
"WseAllowHomePageLinks",
"WseAlertAdministrators",
"WseRemoteAccessUsers",
"WseInvisibleToDashboard",
"WseManagedGroups",
"RAS and IAS Servers",
"Performance Monitor Users",
"Incoming Forest Trust Builders",
"Distributed COM Users",
"Domain Computers",
"Account Operators",
"Replicator",
"Cryptographic Operators",
"Allowed RODC Password Replication Group",
"RDS Endpoint Servers",
"Cloneable Domain Controllers",
"Access Control Assistance Operators",
"Protected Users",
"Performance Log Users",
"Read-only Domain Controllers",
"Backup Operators",
"Domain Guests",
"Event Log Readers",
"Storage Replica Administrators",
"Key Admins",
"Enterprise Key Admins",
"System Managed Accounts Group",
"Remote Management Users",
"Server Operators",
"Domain Users",
"Certificate Service DCOM Access",
"Remote Desktop Users",
"Windows Authorization Access Group",
"Guests",
"Users",
"Domain Controllers",
"Network Configuration Operators",
"IIS_IUSRS",
"Domain Admins",
"Hyper-V Administrators",
"Denied RODC Password Replication Group",
"RDS Remote Access Servers",
"RDS Management Servers",
"Enterprise Admins",
"Terminal Server License Servers",
"Print Operators",
"Schema Admins",
"Group Policy Creator Owners",
"Enterprise Read-only Domain Controllers",
"Administrators",
"Cert Publishers",
"Pre-Windows 2000 Compatible Access",
"admins",
"RTCComponentUniversalServices",
"sw2",
"sw3",
"sw4",
"sw5",
"sw6",
"sw7",
"sw8",
"sw9",
"sw11",
"sw12",
"sw13",
"sw14",
"sw15",
"sw16",
"sw17",
"sw18",
"sw19",
"sw20",
"sw21",
"sw22",
"sw23",
"sw24",
"sw1",
"sw10",
"sw26",
"sw-fin",
"KLOperators",
"itcomputer",
"itcomputer2",
"WINS Users",
"Session Directory Computers",
"HelpServicesGroup",
"DnsUpdateProxy",
"SQLServer2005MSSQLUser$TIDASO-GC00-01$MICROSOFT##SSEE",
"SQLServer2005MSFTEUser$TIDASO-GC00-01$MICROSOFT##SSEE",
"WSUS Reporters",
"WSUS Administrators",
"SQLServer2005MSSQLUser$CAIROS-00GC-001$MICROSOFT##SSEE",
"SQLServer2005MSFTEUser$CAIROS-00GC-001$MICROSOFT##SSEE",
"helpdisk",
"DB2USERS",
"USbEnable",
"insightadmins",
"Branch Manager",
"KLAdmins",
"bank finance",
"Sheq",
"Terminal Server Computers",
"Web",
"misreport-user",
"it-network",
"IIS_WPG",
"credit internet",
"Cairo-internet",
"Internet-Finance",
"123",
"insightuser",
"SCCM",
"MIISPasswordSet",
"HQ-Credit",
"Audit-Shares",
"support vpn",
"DHCP Users",
"ChangeAuditor Operators - DEFAULT",
"Internet-SupperUser",
"devloper",
"SERVICE-CBE",
"Internet-Admin",
"Credit-Supervisor",
"MISRMAKASSA",
"ofac",
"Garden-City-tiller",
"blue",
"Garden-City Branche",
"Financial Dept",
"maximousers",
"NetworkAdmins",
"dev-internet",
"credit-shares",
"Cairo.Credit",
"sqladmins",
"TelnetClients",
"Fin-Shares",
"MOBASHER",
"DB2IADM",
"Banking-observation Dept",
"Device admin",
"Tivoli_Admin_Privileges",
"General-Ledger Dept",
"Balance Dept",
"Developer-internet",
"DB2ADMINS",
"Provisions-taxes-capital Dept",
"ChangeAuditor Administrators - DEFAULT",
"DHCP Administrators",
"sw25",
"VISA",
"SCBCBE",
"Correspondences Dept",
"Personnel",
"Swift1",
"HelpLibraryUpdaters",
"CBE ISE computer",
"Central Bank ISE Computer",
"Managment ISE Computer",
"Media-communication ISE Comuter",
"RETAIL UNIT",
"SHEQ ISE Computer",
"Assiut ISE Computer",
"Center Cash ISE Computer",
"Menia ISE Computer",
"SHARM ISE Computer",
"Sokhna ISE Computer",
"Operation ISE Computer",
"MANIAL ISE USER",
"6OCTU ISE Computer",
"MAADI ISE Computer",
"RTCProxyUniversalServices",
"RTCUniversalSBATechnicians",
"RTCSBAUniversalServices",
"CSResponseGroupAdministrator",
"CSResponseGroupManager",
"CSLocationAdministrator",
"CSArchivingAdministrator",
"CSViewOnlyAdministrator",
"CSHelpDesk",
"CSPersistentChatAdministrator",
"SQLServer2005SQLBrowserUser$SKYPE",
"RTCHSUniversalServices",
"RTCUniversalConfigReplicator",
"RTCUniversalUserAdmins",
"$DUPLICATE-11b3b4",
"WinRMRemoteWMIUsers__",
"$DUPLICATE-11d8cf",
"MSCC",
"IS CORE",
"mis-user-admin",
"internet-swift",
"stock-internet",
"vpn ext law",
"It-Admin ISE User",
"MANIAL ISE COMPUTER",
"CBE ISE User",
"SUEZB ISE User",
"BAD DEBTS ISE User",
"ISMAL ISE Computer",
"Investment ISE User",
"Documentation ISE User",
"SHARM  ISE User",
"VISA ISE Computer",
"MAADI ISE User",
"Legal ISE Computer",
"vpn developer",
"BOARD ISE User",
"OBOUR ISE Computer",
"Internal Audit ISE Computer",
"vpn system admin",
"CREDIT RISK ISE User",
"OBOUR ISE User",
"OPERATION CENTER ISE Computer",
"Assiut ISE User",
"INSPECTION ISE User",
"GIZAB ISE Computer",
"SUEZB ISE Computer",
"DMITA ISe Computer",
"vpn network admin",
"CAIRO ISE User",
"HELIO ISE Computer",
"ALEXA ISE User",
"AUDIT ISE User",
"TANTA ISE User",
"SMOHA ISE Computer",
"Network administrator department",
"CREDIT ISE User",
"Bank Operation ISE User",
"CREDIT ISE Computer",
"PSAID ISE User",
"Assets ISE User",
"FSTAT ISE User",
"Internal Audit ISE User",
"Compliance ISE Computer",
"SHEQ ISE User",
"Legal ISE User",
"BKUPS ISE Computer",
"It-Admin ISE Computer",
"Internet Finance Bayment",
"FOREIGN AFFAIRS ISE Computer",
"PERSONNEL ISE COmputer",
"HELIO ISE User",
"System administrator department",
"GARDEN-CITY ISE User",
"AUDIT ISE Computer",
"TANTA ISE Computer",
"Misr-Makasa ISE Computer",
"MANSOURA ISE User",
"6OCTU ISE User",
"Center Cash ISE User",
"CAIRO ISE Computer",
"CREDIT RISK ISE Computer",
"VISA ISE User",
"ALEXA ISE Computer",
"Bank Operation ISE Computer",
"Engineering ISE Computer",
"INSURANCE ISE User",
"AMRIA ISE User",
"Menia ISE User",
"MANSOURA ISE Computer",
"SADAT ISE User",
"OPERATION CENTER ISe User",
"MARKET-RISK ISE Computer",
"Dealing Room ISE User",
"Security ISE Computer",
"SMOHA ISE User",
"SHOBRA ISE Computer",
"INSURANCE ISE Computer",
"Misr-Makasa ISE User",
"Head Bransh manager ISE User",
"RETAIL UNIT ISE User",
"FINANCIAL ISE Computer",
"NASRC ISE Computer",
"Relation ISE Computer",
"SPHNX ISe Computer",
"Epay",
"BARAB ISE User",
"OURBA ISE Computer",
"MARKET-RISK ISE User",
"Dealing Room ISE Computer",
"Swift ISE User",
"AMRIA ISE Computer",
"DOKKI ISE Computer",
"GARDEN-CITY ISE Computer",
"Engineering ISE User",
"GIZAB ISE User",
"Relation ISE User",
"DMITA ISE User",
"ASHER ISe User",
"Managment ISE User",
"Admin ISE computer",
"PERSONNEL ISE User",
"MOHND ISE User",
"FINANCIAL ISE User",
"Operation department",
"RETAIL UNIT ISE Computer",
"MOHND ISE Computer",
"Investment ISE Computer",
"Sokhna ISE User",
"INSPECTION ISE Computer",
"Security ISE User",
"BOARD ISE Computer",
"NASRC ISE User",
"BAD DEBTS ISE Computer",
"Swift ISE Computer",
"Compliance ISE User",
"FSTAT ISE Computer",
"DOKKI ISE User",
"ISMAL ISE User",
"Central Bank ISE User",
"BARAB ISE Computer",
"Media-communication ISE User",
"BKUPS ISE Use",
"SHOBRA ISE User",
"SPHNX ISE User",
"Admin ISE user",
"Financial -Investment Dept",
"Documentation ISE Computer",
"OURBA ISE User",
"FOREIGN AFFAIRS ISE User",
"RTCUniversalGlobalWriteGroup",
"Skype for Business",
"Business-Process&Developments ISE Computers",
"FINANCE&INVEST ISE USERS",
"RTCUniversalGlobalReadOnlyGroup",
"internet-web",
"it-operation",
"ISE TEST upgrade",
"Internet-DHL",
"SMEs ISE Computer",
"SMEs risk",
"RTCUniversalServerAdmins",
"internet-Dealing2",
"RETAIL-RISK ISE User",
"SADAT ISE Computer",
"internet-manager",
"vpn ext temenos",
"CSUserAdministrator",
"ASHER ISE Computer",
"RTCUniversalServerReadOnlyGroup",
"Retail-Internet",
"internet-dev",
"internet-Shobra",
"portsaid",
"Internet-CBE",
"PSAID ISE Computer",
"CSServerAdministrator",
"CSAdministrator",
"Business-Process&Developments ISE Users",
"IBM_Storage_operations",
"CSVoiceAdministrator",
"RTCUniversalUserReadOnlyGroup",
"internet-NoQuta",
"FOREIGN AFFAIRS",
"Head Bransh manager ISE Computer",
"SMEs ISE User",
"prtest",
"Ext VPN Insight",
"IBM_Storage_Admins group",
"internet-secretary",
"Internet-Loans",
"FINANCE&INVEST ISE COMPUTER",
"internet-users",
"Internet-Dealing",
"RTCUniversalReadOnlyAdmins",
"Call center ISE User",
"fawary-vpn",
"Investment-Employees",
"RETAIL-RISK ISE Computer",
"Call Center",
"Call-Center-R",
"Citrix Remote DeskTop",
"Corporate-Finance-Employees",
"$DUPLICATE-1257ed",
"Retail-Risk",
"Corporate-Finance-Managers",
"Corpay",
"internet-operation",
"IT-developer",
"Call Center ISE Computer",
"Internet Google Translat",
"Market Risk",
"SASusers",
"Internet-SubManager",
"Call-Center-RW",
"Visa-Dep",
"Investment-Managers",
"Help Desk",
"investigation",
"BPD-Full",
"vpn ext billing",
"BPD-ReadOnly",
"E&Young",
"SCBIT",
"PB&A",
"VPN ISE User",
"hq vpn",
"assests",
"DnsAdmins",
"Central-Bank",
"CityStars Branche",
"Internet inspection",
"Benisuef Branche",
"Assuit branche",
"vpn web developer",
"Gelem Branche",
"vpn operation",
"Manial Branche",
"VPN Laserfiche",
"vpn-web-developer",
"VPNExtservices",
"Internet Media-communication",
"vpn-branch",
"Mansoura",
"share folder",
"Swift Dep",
"Acoount Opening",
"VPN HR",
"VPN Swift",
"Vpn-Remot1",
"Approval Garden",
"Suez Branch",
"6Octu Branche",
"Ahrar Branche",
"Al-Hosary Branche",
"Alex Branche",
"AMRIA Branche",
"BARAB Branche",
"BKUPS Branche",
"Cairo Branche",
"DMITA Branche",
"Dokii Group",
"FSTAT Group",
"Gizab Branche",
"HELIO Branche",
"Ismail Group",
"Ismail-Zayed Branche",
"MAADI Branche",
"Madinaty Branche",
"MaglesEldawla Branche",
"Makram Ebeid Branche",
"Mansoura Branche",
"MOHND Branche",
"Nasrc Branche",
"SADAT Branche",
"SHARM Branche",
"Qena Branche",
"TANTA Branche",
"Obour Branche",
"OURBA branche",
"Sokhna-Economic Branche",
"SHOBRA Branche",
"Roushdy Branche",
"P-Tawfik branche",
"SMOHA Branche",
"Sokhna Branche",
"SPHINX Branche",
"Tagamu Branche",
"Top90 Branche",
"HelpDesk Remote",
"Operation Remote",
"Tivoli remote",
"SMES Support",
"Varadmin",
"Varoper",
"IFRS-VPNGroup",
"Smash Group",
"Fujitsu-Group",
"openshift-admins",
"openshift-users",
"Legal-Group",
"ITSS-GROUP",
"VISA-RW",
"VISA-R",
"ECR",
"Temenos-India",
"BankSharing-Group-RW",
"BankSharing-Group-R",
"Internet-CallCenter",
"Security-Group",
"Credit-pc",
"Operation-RW",
"Foreign-Affirs-RDP",
"HQExternal-Credit",
"RISK-External",
"System Remote",
"Digital Team",
"New Admin",
"FTP",
"MW",
"Retail-card",
"Medical",
"internet-linkedin",
"internet-legal",
"$DUPLICATE-12b389",
"IT Manager",
"$DUPLICATE-12b38a",
"SME'S-Support-R",
"SME'S-Support-RW",
"RetailRisk-Colliction and recovery",
"IT-Oracle",
"IT-Dep",
"InfoSec",
"Internet-operationyoutube",
"FILE-SERVER-GROUP",
"Call-Center-TeamLeaders",
"Organization Management",
"Recipient Management",
"View-Only Organization Management",
"Public Folder Management",
"UM Management",
"Help Desk1",
"Records Management",
"Discovery Management",
"Server Management",
"Delegated Setup",
"Hygiene Management",
"Compliance Management",
"Security Reader",
"Security Administrator",
"Exchange Servers",
"Exchange Trusted Subsystem",
"Managed Availability Servers",
"Exchange Windows Permissions",
"ExchangeLegacyInterop",
"$EER410-0E0HPVJ1GFKR",
"Areebah",
"Group Test-1-796766086",
"6 October City Branch",
"Admin Affairs",
"Admin Affairs-11053097676",
"Bad Debts",
"Credit",
"Credit Risk",
"Treasury Group",
"Corporate Finance",
"Financial",
"FOREIGN AFFAIR",
"InfoSec Group",
"INSURANCE",
"Internal Audit",
"Investment",
"Legal Group",
"Security",
"Swift Group",
"Treasury Operation",
"Business-Process&Developments",
"Giza Branch",
"Heliopolis Branch",
"Obour Branch",
"Borg  Branch",
"6Octu Branch",
"Dmita Branch",
"Manial Branch",
"Tagamu Branch",
"Ahrer Branch",
"Alex Branch",
"Al-Hosary Branch",
"Amria Branch",
"Arkan Branche",
"Arkan Branch",
"Asher Branch",
"ASHER Branche",
"Compliance Group",
"Engineering",
"Inspection",
"Investigation Group",
"Assiut Branch",
"Market Risk Group",
"Media Communication",
"BENISUEF Branch",
"Telnet",
"Cairo Branch",
"Mansoura Branch",
"Menia Branch",
"Mohandeseen Branch",
"Nasr City Branch",
"Portfolio",
"Public Relations",
"Retail Risk",
"Retail Group",
"SME Business",
"SME's Risk",
"Visa Group",
"Call Center Department",
"Center Cash",
"Operation Center",
"IT-Internet Develop",
"IT-Admin",
"VPN-SAS",
"VPN-DataGear",
"IT_HelpDesk",
"IT_Develober",
"IT_Operation",
"IT_Network",
"IT-Staff",
"IT-Access Managment",
"Admin Support",
"Doki Branch",
"Fstat Bransh",
"City-Stars Branch",
"Garden City Branch",
"Gleem Branch",
"Ismailia Branch",
"IsmZayed Branch",
"Maadi Branch",
"Madinaty.Branch",
"MaglesEldawla.Branch",
"Makram Ebied Branch",
"PortTawfik Branch",
"Oruba Branch",
"Port Said Branch",
"Qena Branch",
"Sadat Branch",
"Sharm Branch",
"Shobra Branch",
"Smash Club",
"Smoha Branch",
"Sokhna Branch",
"Sokhna-Economic Branch",
"Sphinx Branch",
"Suez-Branch",
"Tanta Branch",
"Top90 Branch",
"Roushdy Branch",
"Account opening",
"System Admins",
"Qradar-Group",
"test",
"IT- System admins-1285029636",
"Mailbox Import Export",
"ACH-EBC",
"AlcoGroup",
"ALL CREDIT ADMIN TEAM",
"Independent-ISO",
"Info",
"Innovation",
"Internal Control Group",
"AMLSupport",
"Asset disposition",
"BankProject",
"Investment Committee",
"BARIQ Fund",
"BDS HUB",
"IT Steering Committee",
"IT-CBE Alerts",
"Branch Compliance officers and Deputies",
"Branch Managers and Deputies",
"Branches-Opening",
"IT-Equipment",
"BranchManagers",
"Business Heads",
"Business planing & Analysis",
"BusinessProcess",
"IT-Security",
"LG - Operation Center",
"Canal zone branches",
"CC-Agents",
"Central Bank",
"Central Managers",
"Loans Group",
"chargeback_dispute",
"Communication",
"Commvault Daily Job Status",
"Complaint Card center",
"Contracts Stakeholder",
"Contact Center Backoffice",
"corporate",
"Cost Efficiency",
"Credit - Risk SME's",
"Credit Admin Team",
"CREDIT-ORUBA",
"custodianx",
"Customer Protection Unit",
"DB-PROJECT",
"DELTA ZONE",
"Delta&Upper-Egypt",
"Denay list",
"Digital.supportxx",
"Digitial-signatre",
"DNA-SYS",
"Documentation",
"Documentation Group",
"local System",
"LocalDomainAdmins",
"LocalDomainServers",
"Manager Branch",
"Elite Group",
"Engineer Dep",
"ERM phase1",
"FATCAgroup",
"Finance",
"Financial Inclusion department",
"Financial Institutions Division",
"Financial Reporting and Control Department",
"Fraud-CardCenter",
"Funds-dep",
"General Accounts",
"Giza Zone",
"Giza Zone Branch Managers",
"Go Green Car replacement",
"Marketing group",
"Misr Makasa",
"MISteam",
"Head Office Managers",
"HO-ICD",
"ibm mail servers Mis",
"IFRS9.committee",
"Mortgage Loans",
"New branches",
"New head Quarter Committee",
"Operational Risk Group",
"ORM-Coordinators",
"OtherDomainServers",
"Personal Affairs",
"pharmacies financing",
"PMO",
"portfolio management and FI risk",
"Rejected outbound Internet mail",
"REMITTANCES DEPT",
"RETAIL CREDIT ADMIN",
"Retail Products Team",
"Retail Risk Collection & Recovery",
"Scb Admin Cars",
"Scb.Admin.BusinessCards",
"SCB MoneyGram",
"Scb.Admin.Archives",
"Scb.Admin.Warehouse",
"scb.infinty",
"Scbank.Admin.Purchasing",
"scbEwallet",
"Scb-Internal Audit",
"scbIT-Operation",
"SCB-Public relations",
"Service Quality Team",
"sharmoffice",
"SMES Support Group",
"Sports",
"Syndication Team",
"T24SCImplementation",
"TopInsurance",
"TopMail",
"TopManagers",
"VACATIN_HR",
"VaultVaultHSGroup-APG00001",
"VaultVaultHSGroup-APG00002",
"Visto Domino Administrative Group",
"Wholesale Bank Heads",
"Zone Manager Branchs",
"Zones_Heads",
"Scb.Admin.Warehouse",
"Scb.Admin.GeneralServices",
"Scb.Admin.Invoices",
"Scb.Admin.Mail",
"CityStars ShareFolder",
"6Oct ShareFolder",
"Ahrar ShareFolder",
"Al-Hosary ShareFolder",
"Alex ShareFolder",
"Amaria ShareFolder",
"Arkan ShareFolder",
"Asher ShareFolder",
"Assiut ShareFolder",
"BorgArab ShareFolder",
"Benisuf ShareFolder",
"BKUPS ShareFolder",
"Cairo ShareFolder",
"Dmita ShareFolder",
"Dokii ShareFolder",
"Fostat ShareFolder",
"Garden-City ShareFolder",
"Gelem ShareFolder",
"Giza ShareFolder",
"Helio ShareFolder",
"Ismail ShareFolder",
"Ismail-Zayed ShareFolder",
"MAADI ShareFolder",
"Madinaty ShareFolder",
"MaglesEldawla ShareFolder",
"Makram Ebeid ShareFolder",
"Manial ShareFolder",
"Mansoura ShareFolder",
"Menia ShareFolder",
"Mohand SherFolder",
"NASRC ShareFolder",
"Obour ShareFolder",
"OURBA ShareFolder",
"P-Tawfik ShareFolder",
"PSAID ShareFolder",
"Qena ShareFolder",
"Roushdy ShareFolder",
"SHARM ShareFolder",
"SHOBRA ShareFolder",
"Smash Club ShareFolder",
"SMOHA ShareFolder",
"Sokhna ShareFolder",
"Sokhna-Economic ShareFolder",
"SPHINX ShareFolder",
"SUEZB ShareFolder",
"Tagamu ShareFolder",
"Tanta ShareFolder",
"Top90 ShareFolder",
"service account",
"Mohandsen Branch",
"Senior Management",
"ICS",
"Foreign",
"Contact Center Department",
"IT-Infrastructure",
"COSO VPN",
"External send not allowed-11730278146",
"LC Import-1-1581031753",
"collection import-1-494352960",
"CBE GROUP",
"Facility Help Desk-12138625995",
"Retail Group-1-1890847007",
"Credit-1360621343",
"Scb.Admin.FixedAsset-11748059101",
"Alco Group-1-770557279",
"All Branches",
"Assets disposition-1-2083640112",
"CIT-1-1558904216",
"Digital Team-1-1173056299",
"Hurghada-R",
"Hurghada-RW",
"Hurghada Branch",
"Sporting-R",
"Sporting-RW",
"Sporting Branch",
"Capital-R",
"Capital-RW",
"Capital Branch"
